### ISSUE TITLE
 Cannot find module 'jsdav'

### ISSUE THREAD

**Issue by ibnishak** [edrex/dav-server#12]
Sorry, I do not know much about this system. I typed `dav-server ~/myFolder` where myFolder has TW5 html files in it. It gave me this error

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'jsdav'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/myName/.npm-global/lib/node_modules/dav-server/index.js:13:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

Any suggestions?

**Comment by jonniestuefer** [comment]
Same here. Don't know anything about nodejs or npm, so haven't managed to fix it.

**Comment by paulmelis** [comment]
It's called jsDAV these days apparently. These changes fix it:

```
--- doh.js	2020-03-13 12:10:08.507921315 +0100
+++ index.js	2020-03-13 11:36:47.346070106 +0100
@@ -1,3 +1,4 @@
+#!/usr/bin/env node
 /*
  * @package dav-server
  * @copyright Copyright(c) 2016 PDXHub <eric AT PDXHub.org>
@@ -9,7 +10,7 @@
 var args = require('minimist')(process.argv.slice(2), {boolean: ['debug','h'], string: ['i', 'p', 'digest', 'realm'], default: {i:'127.0.0.1', p:8000}});
 var fs = require('fs');
 var path = require('path');
-var jsDAV = require("jsdav");
+var jsDAV = require("jsDAV");
 
 var usage = "dav-server [--debug] [-i LISTEN_IP] [-p PORT] [--digest HTDIGEST_FILE --realm AUTH_REALM] rootDir";
 
@@ -27,14 +28,14 @@
 
 var config = {
   node: rootDir,
-  locksBackend: require("jsdav/lib/DAV/plugins/locks/fs").new(rootDir)
+  locksBackend: require("jsDAV/lib/DAV/plugins/locks/fs").new(rootDir)
 }
 
 if (args.digest || args.realm) {
   if (!args.digest || !args.realm ) {
     exitMsg("--digest and --realm are corequisite.", 1);
   }
-  config.authBackend = require("jsdav/lib/DAV/plugins/auth/file").new(args.digest);
+  config.authBackend = require("jsDAV/lib/DAV/plugins/auth/file").new(args.digest);
   config.realm = args.realm;
 }
```
